"""
main.py
=======
Executable CLI driver for the complete EduScript Compiler and Interpreter pipeline.

Pipeline Architecture:
1. Lexical Analysis       (lexer.py)              -> Token stream
2. Syntax Analysis        (parser.py, ast_nodes)  -> Abstract Syntax Tree (AST)
3. Semantic Analysis      (semantic_analyzer.py)  -> Scoped Symbol Table & Type Checking
4. Intermediate Code      (tac_generator.py)      -> Three-Address Code (TAC) IR
5. Execution Engine       (interpreter.py)        -> TAC Virtual Machine / AST Interpreter

Usage:
    python main.py                              # Runs configured source_file from config.json
    python main.py <source_file.custom>         # Runs specified source file
    python main.py <source_file> --tokens       # Displays Lexical Tokens
    python main.py <source_file> --ast          # Displays Abstract Syntax Tree
    python main.py <source_file> --symbols      # Displays Scoped Symbol Table
    python main.py <source_file> --tac          # Displays Three-Address Code IR
    python main.py <source_file> --all          # Displays all compiler stages in detail
"""

import sys
import json
import argparse
from pathlib import Path
from typing import Dict, Any, List

from lexer import Lexer, Token, LexicalError
from parser import Parser, ParseError
from ast_nodes import ASTPrinter, Program
from symbol_table import SymbolTable
from semantic_analyzer import SemanticAnalyzer, SemanticError, SemanticWarning
from tac_generator import TACGenerator, TACProgram
from interpreter import TACInterpreter, ASTInterpreter, ExecutionResult


def load_json_file(file_path: Path) -> Dict[str, Any]:
    """Loads and parses a JSON file with error handling."""
    if not file_path.exists():
        print(f"[Error] Required file not found: {file_path}", file=sys.stderr)
        sys.exit(1)
    try:
        with open(file_path, "r", encoding="utf-8") as f:
            return json.load(f)
    except json.JSONDecodeError as e:
        print(f"[Error] Failed to parse JSON file {file_path}: {e}", file=sys.stderr)
        sys.exit(1)


def resolve_path(base_dir: Path, target_path_str: str) -> Path:
    """Resolves relative paths with respect to base_dir."""
    p = Path(target_path_str)
    if p.is_absolute():
        return p
    return (base_dir / p).resolve()


def print_token_table(tokens: List[Token]):
    """Prints the list of tokens in a formatted table."""
    print("=" * 78)
    print(f"{'LINE:COL':<10} | {'TOKEN TYPE':<12} | {'LEXEME':<22} | {'CANONICAL MEANING'}")
    print("=" * 78)

    for token in tokens:
        canon_display = f"canonical: {token.canonical}" if token.canonical else "-"
        pos = f"{token.line}:{token.column}"
        lexeme_disp = token.lexeme if len(token.lexeme) <= 22 else token.lexeme[:19] + "..."
        print(f"{pos:<10} | {token.type:<12} | {lexeme_disp:<22} | {canon_display}")

    print("=" * 78)


def main():
    arg_parser = argparse.ArgumentParser(
        description="EduScript Compiler & Interpreter - Complete End-to-End Compiler Pipeline."
    )
    arg_parser.add_argument(
        "source_file",
        nargs="?",
        default=None,
        help="Path to EduScript / custom source file (defaults to config.json setting)."
    )
    arg_parser.add_argument(
        "--config",
        "-c",
        default="config.json",
        help="Path to configuration JSON file (default: config.json)."
    )
    arg_parser.add_argument(
        "--tokens",
        "-t",
        action="store_true",
        help="Display the token stream generated by the Lexer."
    )
    arg_parser.add_argument(
        "--ast",
        "-a",
        action="store_true",
        help="Display the hierarchical Abstract Syntax Tree (AST)."
    )
    arg_parser.add_argument(
        "--symbols",
        "-s",
        action="store_true",
        help="Display the scoped Symbol Table generated during Semantic Analysis."
    )
    arg_parser.add_argument(
        "--tac",
        "--ir",
        action="store_true",
        help="Display generated Three-Address Code (TAC) Intermediate Representation."
    )
    arg_parser.add_argument(
        "--all",
        "-v",
        action="store_true",
        help="Display output from all stages of the compiler pipeline."
    )
    arg_parser.add_argument(
        "--ast-run",
        action="store_true",
        help="Execute via AST Tree-Walk Interpreter instead of TAC Virtual Machine."
    )

    args = arg_parser.parse_args()

    # Determine base directory
    config_path = Path(args.config).resolve()
    base_dir = config_path.parent if config_path.exists() else Path.cwd()

    # 1. Load configuration
    if config_path.exists():
        config = load_json_file(config_path)
    else:
        config = {}

    mapping_path = resolve_path(base_dir, config.get("keyword_mapping_file", "keyword_mapping.json"))
    tokens_path = resolve_path(base_dir, config.get("default_tokens_file", "default_tokens.json"))

    if args.source_file:
        source_path = Path(args.source_file).resolve()
    else:
        source_path = resolve_path(base_dir, config.get("source_file", "example.custom"))

    keyword_mapping = load_json_file(mapping_path) if mapping_path.exists() else {}
    default_tokens = load_json_file(tokens_path) if tokens_path.exists() else {}
    lexer_settings = config.get("lexer_settings", {})

    if not source_path.exists():
        print(f"[Error] Source file not found: {source_path}", file=sys.stderr)
        sys.exit(1)

    try:
        with open(source_path, "r", encoding="utf-8") as f:
            source_code = f.read()
    except Exception as e:
        print(f"[Error] Could not read source file {source_path}: {e}", file=sys.stderr)
        sys.exit(1)

    show_all = args.all
    show_tokens = args.tokens or show_all
    show_ast = args.ast or show_all
    show_symbols = args.symbols or show_all
    show_tac = args.tac or show_all

    print("\n" + "=" * 78)
    print("                 EDUSCRIPT COMPILER & INTERPRETER PIPELINE")
    print("=" * 78)
    print(f"Source File       : {source_path.name}")
    print(f"Keyword Mappings  : {len(keyword_mapping)} mapped entries")
    print("=" * 78)

    # -------------------------------------------------------------------------
    # STAGE 1: LEXICAL ANALYSIS
    # -------------------------------------------------------------------------
    lexer = Lexer(
        keyword_mapping=keyword_mapping,
        token_definitions=default_tokens,
        settings=lexer_settings
    )
    tokens, lex_errors = lexer.tokenize(source_code)

    if show_tokens:
        print(f"\n[PHASE 1] LEXICAL ANALYSIS ({len(tokens)} tokens generated):")
        print_token_table(tokens)
        type_counts = {}
        for tok in tokens:
            type_counts[tok.type] = type_counts.get(tok.type, 0) + 1
        counts_str = ", ".join(f"{k}: {v}" for k, v in sorted(type_counts.items()))
        print(f"Token Breakdown: {counts_str}")

    if lex_errors:
        print("\n" + "!" * 78)
        print(f"LEXICAL ERRORS ENCOUNTERED: {len(lex_errors)}")
        print("!" * 78)
        for err in lex_errors:
            print(f"  * {err}")
        print("!" * 78 + "\n")
        sys.exit(1)

    # -------------------------------------------------------------------------
    # STAGE 2: SYNTAX ANALYSIS (PARSING & AST)
    # -------------------------------------------------------------------------
    parser = Parser(tokens)
    ast, parse_errors = parser.parse()

    if parse_errors:
        print("\n" + "!" * 78)
        print(f"SYNTAX ERRORS ENCOUNTERED: {len(parse_errors)}")
        print("!" * 78)
        for err in parse_errors:
            print(f"  * {err}")
        print("!" * 78 + "\n")
        sys.exit(2)

    if show_ast and ast:
        print("\n[PHASE 2] ABSTRACT SYNTAX TREE (AST):")
        print("=" * 60)
        print(ASTPrinter().print(ast))
        print("=" * 60)

    # -------------------------------------------------------------------------
    # STAGE 3: SEMANTIC ANALYSIS & SYMBOL TABLE
    # -------------------------------------------------------------------------
    semantic_analyzer = SemanticAnalyzer()
    symbol_table, semantic_errors, semantic_warnings = semantic_analyzer.analyze(ast)

    if show_symbols:
        print("\n[PHASE 3] SCOPED SYMBOL TABLE:")
        print(symbol_table.format_table())

    if semantic_warnings:
        print("\nSEMANTIC WARNINGS:")
        for warn in semantic_warnings:
            print(f"  ? {warn}")

    if semantic_errors:
        print("\n" + "!" * 78)
        print(f"SEMANTIC ERRORS ENCOUNTERED: {len(semantic_errors)}")
        print("!" * 78)
        for err in semantic_errors:
            print(f"  * {err}")
        print("!" * 78 + "\n")
        sys.exit(3)

    # -------------------------------------------------------------------------
    # STAGE 4: INTERMEDIATE REPRESENTATION (TAC)
    # -------------------------------------------------------------------------
    tac_gen = TACGenerator()
    tac_program = tac_gen.generate(ast)

    if show_tac:
        print("\n[PHASE 4] THREE-ADDRESS CODE (TAC) INTERMEDIATE REPRESENTATION:")
        print(tac_program.format_listing())

    # -------------------------------------------------------------------------
    # STAGE 5: PROGRAM EXECUTION
    # -------------------------------------------------------------------------
    print("\n[PHASE 5] PROGRAM EXECUTION:")
    if args.ast_run:
        ast_interpreter = ASTInterpreter()
        result = ast_interpreter.interpret(ast)
    else:
        tac_interpreter = TACInterpreter(tac_program)
        result = tac_interpreter.run()

    result.print_summary()

    if not result.success:
        sys.exit(4)

    sys.exit(0)


if __name__ == "__main__":
    main()
